version: '3.3'

services:
  bionic:
    image: kasmweb/manager:develop
    shm_size: '512mb'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PW: '${PASSWORD}'
    ports:
      - 6901
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.2'
          memory: 128M
        limits:
          cpus: '4.0'
          memory: 4G

