version: '3.3'
services:
  kasm_web:
    image: ipvsix/ubuntu-desktop:jun22
    shm_size: '512mb'
    volumes:
      - nfs_kasm_home:/home/ubuntu/kasm_web
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      VNC_PW: '${PASSWORD}'
    ports:
      - 6901
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
        limits:
          cpus: '4.0'
          memory: 4G
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.${APPNAME}-https.rule=Host(`${APPNAME}.${DOMAIN}`)
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80

volumes:
  kasm-user-home:
    external: true

# PASSWORD=password1234$
# APPNAME=node0
# DOMAIN=cpe.en.rmutt.ac.th