version: '3.3'
services:
  bionic:
    image: kasmweb/ubuntu-bionic-desktop:1.10.0-rolling
    shm_size: '512mb'

    volumes:
      - home_volume:/home/kasm-user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      VNC_PW: '${PASSWORD}'
    ports:
      - 6901
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.2'
          memory: 512M
        limits:
          cpus: '4.0'
          memory: 4G
      
volumes:
  home_volume:

