version: '3.3'
services:
  kasm_web:
#    image: kasmweb/firefox:1.10.0-rolling
#    image: kasmweb/chrome:1.10.0-rolling
    image: kasmweb/postman:1.10.0-rolling
    shm_size: '512mb'
    environment:
      VNC_PW: '${PASSWORD}'
    ports:
      - 6901
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.2'
          memory: 256M
        limits:
          cpus: '4.0'
          memory: 4G

